n = str(input('Digite algo: '))
print(n)
print(n.isalnum())
print(n.isalpha())
print(n.isascii())
print(n.isdigit())
print(n.islower())
print(n.isdecimal())
print(n.isidentifier())
print(n.isnumeric())
print(n.isprintable())
print(n.isspace())
print(n.istitle())


